### ISSUE TITLE
Save the generated attack images

### ISSUE THREAD

**Issue by AOOOOOA** [Wuziyi616/IF-Defense#10]
Hi ziyi,

sorry for bothering you.  Can the generated attack images be saved? If yes, which config parameters should I modify?

Thanks!

**Comment by Wuziyi616** [comment]
The code for saving attacked point clouds are [here](https://github.com/Wuziyi616/IF-Defense/blob/4b1d69d03d76e8d5ca1b4d45f81a8c9c60791263/baselines/attack_scripts/targeted_perturb_attack.py#L162-L174)
