### ISSUE TITLE
Hybrid training data

### ISSUE THREAD

**Issue by jamesliu609** [Wuziyi616/IF-Defense#14]
Hi ziyi. In hybrid training, you provided MN40, convonet_opt_MN40, onet_opt-MN40, onet_remesh-MN40 and attack_data.npz used for all attacks. Could you please tell me if these three defense data (convonet_opt_MN40, onet_opt-MN40. onet_remesh-MN40) are from IF-Defense used on attack_data.npz or MN40?

**Comment by Wuziyi616** [comment]
The three defense data are used to train base point cloud networks to close the domain gap of each defense method. They are not used in attack. If you just want to run attack algorithms, you do not need them

**Comment by jamesliu609** [comment]
Thanks for the answer, but it bothers me how to generate the data(convonet_opt_MN40、onet_opt-MN40、onet_remesh-MN40). Did they get it with IF-defense acting on the raw point cloud MN40 or the raw data used by the attack?

**Comment by Wuziyi616** [comment]
IF-defense acting on the raw point cloud MN40. Basically applying the defense on raw point clouds to get a "defended" version of the point clouds, and train a base point cloud on a mix of them (original + "defended" version)

**Comment by jamesliu609** [comment]
Oh, I get it. Thanks for your patience in answering!
