### ISSUE TITLE
How to train ConvONet on other datasets？

### ISSUE THREAD

**Issue by jamesliu609** [Wuziyi616/IF-Defense#16]
Hi, we want to apply IF-defense to our own dataset, how do I train it?

**Comment by Wuziyi616** [comment]
If you have an attacked version of the point cloud, then just run our IF-Defense on it and get a defended version of point cloud, following the commands listed in README. Did you have any trouble doing this?

**Comment by jamesliu609** [comment]
If we want to apply the ConvONet version of IF-Defense to the ShapeNet dataset, can we just use the ConvONet weight you provided?[https://github.com/Wuziyi616/IF-Defense/tree/main/ConvONet#:~:text=We%20provide%20the%20ConvONet%20weight%20used%20in%20our%20experiments%20here.%20Please%20download%20it%20and%20put%20it%20into%20the%20pretrain/%20folder.](url)

**Comment by jamesliu609** [comment]
If we want to apply the ConvONet version of IF-Defense to the ShapeNet dataset, can we just use the ConvONet weight you provided in ConvONet?

**Comment by Wuziyi616** [comment]
If I remember correctly, that weight was trained on ModelNet by me. If you want to experiment on ShapeNet, you can take a look at the [official ShapeNet weight](https://github.com/autonomousvision/convolutional_occupancy_networks?tab=readme-ov-file#shapenet).
