### ISSUE TITLE
How to perform the ConvOnet？

### ISSUE THREAD

**Issue by jamesliu609** [Wuziyi616/IF-Defense#17]
After I try to go into ConvONet and install `python setup.py build_ext --inplace` using gcc5.5, then execute ：`CUDA_VISIBLE_DEVICES=0 python opt_defense.py --sample_npoint=1024 -- train=False --rep_weight=500.0 --data_root=path/to/adv_data.npz` 
then reported error: `oserror: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory`, I tried many ways and could not solve it.
In addition the pre-training weights` convonet.pth` are placed in the folder under the` ConvONet/pretrain/ `folder?

**Comment by jamesliu609** [comment]
Sorry, I've fixed the problem.

**Comment by Wuziyi616** [comment]
Glad to know that you have fixed it.
