### ISSUE TITLE
Question about the adaptive attack ?

### ISSUE THREAD

**Issue by cuge1995** [Wuziyi616/IF-Defense#7]
Hey, Ziyi.
We proposed the [IT-Defense](https://github.com/cuge1995/IT-Defense) recently, which utilized the network’s property (such as permutation invariant of input point cloud for Pointnet) to defend attacks. But we don't know how to design an adaptive attack for our defense, could you give any suggestions?
 
Best wishes!
Jinlai

**Comment by Wuziyi616** [comment]
Hi! Maybe we can go to the issue session of your repo and chat using Chinese. Do you think that works?

**Comment by cuge1995** [comment]
That's ok!
Thanks.

**Comment by cuge1995** [comment]
或者也可以加我微信聊，我的微信是cuge1995。
我后面的[Mesh Attack](https://github.com/cuge1995/Mesh-Attack)也很大程度上受益于你开源的baseline，超级感谢！
