### ISSUE TITLE
the location of /pretrain folder

### ISSUE THREAD

**Issue by AOOOOOA** [Wuziyi616/IF-Defense#9]
_Pre-trained Victim Models
We provided the pre-trained weights for the victim models used in our experiments. Download from here and uncompress them into pretrain/. You can also train your victim models by yourself and put them into the folder.

Note that, if you want to use your own model/weight, please modify the variable called 'BEST_WEIGHTS' in config.py._

Hi , I saw this in the readme file in /baseline folder. But I can't find the pretrain folder, does it change to another name?

**Comment by AOOOOOA** [comment]
> _Pre-trained Victim Models We provided the pre-trained weights for the victim models used in our experiments. Download from here and uncompress them into pretrain/. You can also train your victim models by yourself and put them into the folder.
> 
> Note that, if you want to use your own model/weight, please modify the variable called 'BEST_WEIGHTS' in config.py._
> 
> Hi , I saw this in the readme file in /baseline folder. But I can't find the pretrain folder, does it change to another name?


Do you mean I should download the pretrain weights and unzip it as /baseline/pretrain?

**Comment by Wuziyi616** [comment]
Yes you are correct. Please download them to `baseline/pretrain/`
